name: joelcasey.com
favicon: null
layout_spectrum: 0.4669470654334873
typography_spectrum: 0.4523746841587126
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.1421351176686585
  lightness: 0.09149374673143029
  saturation: 0.8674508673138916
  rhythmicContrast: 0.8826981342863292
purpose: []
